language: php

php:
#  - 5.4
#  - 5.5
  - 5.6
  - 7.0

#matrix:
#    allow_failures:
#        - php: 7.0

sudo: false

env: DB_DATABASE=vain DB_USERNAME=travis DB_PASSWORD=

services:
  - memcached

install:
  - composer install --no-interaction --prefer-source

script: vendor/bin/phpunit

after_script:
  - vendor/bin/test-reporter

notifications:
  slack: parabelcon:AfqrMDyoikewLql9defXlWHW

addons:
  code_climate:
    repo_token: cadcd37f6ed1b8e5570c6e3ed2eff62dee3aa445b9fbeb96de5f659c83176d99